version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=MY_DB
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d MY_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://server:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  default:
    driver: bridge